/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mark' at '12/28/15 4:08 PM' with Gradle 2.9
 *
 * @author mark, @date 12/28/15 4:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
